name: Build Windows

on: [push, pull_request]


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
    - name: update pacman
      run: msys2do pacman -Syu --noconfirm
    - name: install chiavdf dependencies
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-libsodium mingw-w64-x86_64-gmp git
    - name: build
      run: msys2do ./install.sh release
#    - name: test qml
#      run: msys2do build/release/bin/monero-wallet-gui --test-qml
