name: Build Windows

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags
    - uses: numworks/setup-msys2@v1
    - name: update pacman
      run: msys2do pacman -Syu --noconfirm
    - name: install chiavdf dependencies
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-python mingw-w64-x86_64-gmp mingw-w64-x86_64-python-pip
    - name: build
      run: msys2do ./install.sh release
#    - name: test qml
#      run: msys2do build/release/bin/monero-wallet-gui --test-qml
