name: Python package


on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install .
    - name: Test vdf
      run: |
        source venv/bin/activate
        python python_bindings/test_verifier.py
    - name: Lint source with flake8
      run: |
        source venv/bin/activate
        pip install flake8
        # ./venv/bin/flake8 python_bindings
        # this isn't working and there are too many warnings to fix quickly

